### PR TITLE
Update vfl convenience function

### PR DESCRIPTION
**Pull request by rmigneco**
This PR re-orders the VFL convenience function so that default parameters are at the end as per Apple's recommendation.

It also updates the Podfile for cocoapods 1.0 compliance.

Currently there is an issue building the tests because the module cannot be imported (either via old school `#import` or new `@import` syntax)

### CODE REVIEW

**Comment by ryang1428** [comment]
You're going to have the same travis issues here as we saw with URBNAlert. Also, this will be a breaking change, mainly for Anthro as they use this a lot. I just used it for the first time in FP in a open PR, so not a huge deal there.

**Comment by rmigneco** [comment]
It's up to the group whether they are open to the change and then I can take a further look at the CI stuff. 

I don't use this particular method in my code right now so I'm indifferent towards it.

**Comment by ryang1428** [comment]
I got the travis builds working-- follow what I had to do in here: https://github.com/urbn/URBNAlert/blob/master/.travis.yml

**Comment by codecaffeine** [comment]
While the API is nicer _(IMO)_, this change:

1. Is a breaking API change.
2. The current implementation is already in production apps.
3. Doesn’t add any functionality.
4. Had already been discussed as a group.

I think the [discussion is good](https://github.com/urbn/uo-ios/pull/1736#discussion_r63688815) and when writing code, we should follow Apple’s rule and put parameters with default parameters at the end.. It’s also something to re-visit **_if_** we make larger change to the VFL convenience methods. For right now, this doesn’t add too much value and affects a large portion of the Anthro code that’s already out in production.

**Comment by jgrandelli** [comment]
To piggy back on @codecaffeine's point we should _ we should follow Apple’s rule and put parameters with default parameters at the end_ *when it is the most appropriate design.* 

Those _rules_ are guidelines and particular implementations or scenarios can sometimes have their own considerations that may or may not outweigh style guidelines.

**Comment by codecaffeine** [comment]
yeah yeah yeah, it’s a **guideline** not a **rule**. My bad. Updated my comment.

**Comment by rmigneco** [comment]
In my most reasonable, non Ray-ge-y explanation, my preference here was to have the required parameters up front and params with default arguments in the back. Why?

- Because the required parameters are the ones that you care about *every time* regardless of your usage. 
- This is especially the case with VFL because you will alway need the format string and your views.  Why apple wrote the method with the param order in its current state? I may never know.
- Since this is a convenience method, what are we really gaining out of maintaining Apple's parameter order?
- As @codecaffeine pointed out, bumping the required params up front makes things feel more natural esp with autocomplete

**Comment by ndis1** [comment]
>Since this is a convenience method, what are we really gaining out of maintaining Apple's parameter order?

When this was first implemented there was concern as how quickly it might be adopted. There is a general aversion to VFL wrappers and custom DSLs. The method was kept as similar as possible to the Apple method to help adopters feel comfortable with the change. It emphasizes that this method is a light wrapper on an Apple function, not a custom VFL DSL.

**Pull request closed without merging**
