### PR TITLE
Merge with dict

### PR DESCRIPTION
**Pull request by KVTaniguchi**
The purpose of this PR is to add the merge function for dictionaries found in the Advanced Swift book.

### CODE REVIEW

**Comment by flippinjoe21** [comment]
Do we want to consider a deep copy?  For instance, given a dict that has a "address" which is another dict on the left.  And given that same type of setup on the right, the address key will always end up with whatever is on the right.

**Comment by KVTaniguchi** [comment]
^ 👍  working on it

**Comment by codecaffeine** [comment]
Didn't like this one? https://github.com/urbn/URBNConvenience/pull/40

**Comment by codecaffeine** [comment]
Also, in swift we really don't need the prefix since we have the module name to disambiguate

**Comment by KVTaniguchi** [comment]
I like having an explicit option, and how it conforms to sequence type.

**Pull request closed without merging**
